"""Embed the existing WebP backgrounds for previews opened with file://.

Run after changing the backgrounds. HTTP previews use the normal image assets;
only direct-file previews load this generated classic-script asset.
"""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    scenes = {}
    for theme in ("light", "dark"):
        path = ROOT / "assets" / "backgrounds" / f"alpine-{theme}.webp"
        scenes[theme] = "data:image/webp;base64," + base64.b64encode(path.read_bytes()).decode("ascii")
    output = ROOT / "assets" / "backgrounds" / "local-scenes.js"
    output.write_text(
        "// Generated by scripts/build_local_scenes.py; used only for file:// previews.\n"
        + "window.PortfolioGlass.localScenes = " + json.dumps(scenes, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {output.relative_to(ROOT)} ({output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
